export const vaadinComponentImports = {
  "vaadin-accordion": ['import "@vaadin/accordion"'],
  "vaadin-app-layout": ['import "@vaadin/app-layout"'],
  "vaadin-drawer-toggle": ['import "@vaadin/app-layout/drawer-toggle.js"'],
  "vaadin-avatar": ['"import "@vaadin/avatar"'],
  "vaadin-avatar-group": ['"import "@vaadin/avatar-group"'],
  "vaadin-button": ['import "@vaadin/button"'],
  "vaadin-checkbox": ['import "@vaadin/checkbox"'],
  "vaadin-checkbox-group": ['import "@vaadin/checkbox"'],
  "vaadin-combo-box": ['import "@vaadin/combo-box"'],
  "vaadin-context-menu": ['import "@vaadin/context-menu"'],
  "vaadin-custom-field": ['import "@vaadin/custom-field"'],
  "vaadin-date-picker": ['import "@vaadin/date-picker"'],
  "vaadin-date-time-picker": ['import "@vaadin/date-time-picker"'],
  "vaadin-details": ['import "@vaadin/details"'],
  "vaadin-dialog": ['import "@vaadin/dialog"'],
  "vaadin-email-field": ['import "@vaadin/email-field"'],
  "vaadin-form-layout": ['import "@vaadin/form-layout"'],
  "vaadin-grid": ['import "@vaadin/grid"'],
  "vaadin-grid-column-group": [
    "import '@vaadin/grid/vaadin-grid-column-group.js'",
  ],
  "vaadin-grid-filter-column": [
    "import '@vaadin/grid/vaadin-grid-filter-column.js'",
  ],
  "vaadin-grid-selection-column": [
    "import '@vaadin/grid/vaadin-grid-selection-column.js'",
  ],
  "vaadin-grid-sort-column": [
    "import '@vaadin/grid/vaadin-grid-sort-column.js'",
  ],
  "vaadin-grid-tree-column": [
    "import '@vaadin/grid/vaadin-grid-tree-column.js';]",
  ],

  "vaadin-horizontal-layout": ['import "@vaadin/horizontal-layout"'],
  "vaadin-icon": ['import "@vaadin/icons"', 'import "@vaadin/icon"'],
  "vaadin-integer-field": ['import "@vaadin/integer-field"'],
  "vaadin-item": ['import "@vaadin/item"'],
  "vaadin-list-box": ['import "@vaadin/list-box"'],
  "vaadin-login-overlay": ['import "@vaadin/login"'],
  "vaadin-menu-bar": ['import "@vaadin/menu-bar"'],
  "vaadin-message-input": ['import "@vaadin/message-input"'],
  "vaadin-message-list": ['import "@vaadin/message-list"'],
  "vaadin-notification": ['import "@vaadin/notification"'],
  "vaadin-number-field": ['import "@vaadin/number-field"'],
  "vaadin-password-field": ['import "@vaadin/password-field"'],
  "vaadin-progress-bar": ['import "@vaadin/progress-bar"'],
  "vaadin-radio-group": ['import "@vaadin/radio-group"'],
  "vaadin-radio-button": ['import "@vaadin/radio-button"'],
  "vaadin-scroller": ['import "@vaadin/scroller"'],
  "vaadin-select": ['import "@vaadin/select"'],
  "vaadin-split-layout": ['import "@vaadin/split-layout"'],
  "vaadin-tabs": ['import "@vaadin/tabs"'],
  "vaadin-tab": ['import "@vaadin/tabs"'],
  "vaadin-text-area": ['import "@vaadin/text-area"'],
  "vaadin-text-field": ['import "@vaadin/text-field"'],
  "vaadin-time-picker": ['import "@vaadin/time-picker"'],
  "vaadin-upload": ['import "@vaadin/upload"'],
  "vaadin-virtual-list": ['import "@vaadin/virtual-list"'],
  "vaadin-vertical-layout": ['import "@vaadin/ordered-layout"'],
};
