export const paletteContent = [
  [
    "<h2>Native HTML</h2>",
    [
      ["a", ["a", "(", ")"]],
      ["article", ["article", "(", ")"]],
      ["aside", ["aside", "(", ")"]],
      ["div", ["div", "(", ")"]],
      ["h1", ["h1", "(", "textContent", "h1 header", "=", ")"]],
      ["h2", ["h2", "(", "textContent", "h2 header", "=", ")"]],
      ["h3", ["h3", "(", "textContent", "h3 header", "=", ")"]],
      ["h4", ["h4", "(", "textContent", "h4 header", "=", ")"]],
      ["h5", ["h5", "(", "textContent", "h5 header", "=", ")"]],
      ["h6", ["h6", "(", "textContent", "h6 header", "=", ")"]],
      ["hr", ["hr", "(", "style", "width:100px;", "=", ")"]],
      ["header", ["header", "(", ")"]],
      ["img", ["img", "(", ")"]],
      ["input text", ["input", "(", "type", "text", "=", ")"]],
      ["input range", ["input", "(", "type", "range", "=", ")"]],
      ["label", ["label", "(", ")"]],
      ["li", ["li", "(", ")"]],
      ["p", ["p", "(", "textContent", "Paragraph", "=", ")"]],
      ["span", ["span", "(", "textContent", "Span", "=", ")"]],
      [
        "ol",
        [
          "ol",
          "(",
          "li",
          "(",
          "textContent",
          "item1",
          "=",
          ")",
          "li",
          "(",
          "textContent",
          "item2",
          "=",
          ")",
          ")",
        ],
      ],
      [
        "ul",
        [
          "ul",
          "(",
          "li",
          "(",
          "textContent",
          "item1",
          "=",
          ")",
          "li",
          "(",
          "textContent",
          "item2",
          "=",
          ")",
          ")",
        ],
      ],
    ],
  ],
  [
    "<h2>Buttons</h2>",
    [
      ["button", ["vaadin-button", "(", ")"]],
      ["checkbox", ["vaadin-checkbox", "(", ")"]],
      [
        "checkbox-group",
        [
          "vaadin-checkbox-group",
          "(",
          "vaadin-checkbox",
          "(",
          ")",
          "vaadin-checkbox",
          "(",
          ")",
          ")",
        ],
      ],
      ["checkbox-group", ["vaadin-checkbox-group", "(", ")"]],
      ["radio-button", ["vaadin-radio-button", "(", ")"]],
      [
        "radio-group",
        [
          "vaadin-radio-group",
          "(",
          "vaadin-radio-button",
          "(",
          ")",
          "vaadin-radio-button",
          "(",
          ")",
          ")",
        ],
        "radio-group",
        ["vaadin-radio-group", "(", ")"],
      ],
      [
        "tabs",
        [
          "vaadin-tabs",
          "(",
          "vaadin-tab",
          "(",
          "textContent",
          "Tab1",
          "=",
          ")",
          "vaadin-tab",
          "(",
          "textContent",
          "Tab2",
          "=",
          ")",
          ")",
        ],
      ],
      ["tab", ["vaadin-tab", "(", ")"]],
    ],
  ],

  [
    "<h2>Fields</h2>",
    [
      ["combo-box", ["vaadin-combo-box", "(", ")"]],
      ["context-menu", ["vaadin-context-menu", "(", ")"]],
      ["custom-field", ["vaadin-custom-field", "(", ")"]],
      ["date-picker", ["vaadin-date-picker", "(", ")"]],
      ["date-time-picker", ["vaadin-date-picker", "(", ")"]],
      ["email-field", ["vaadin-email-field", "(", ")"]],
      ["integer-field", ["vaadin-integer-field", "(", ")"]],
      ["item", ["vaadin-item", "(", ")"]],
      ["list-box", ["vaadin-list-box", "(", ")"]],
      ["number-field", ["vaadin-number-field", "(", ")"]],
      ["password-field", ["vaadin-password-field", "(", ")"]],
      ["select", ["vaadin-select", "(", ")"]],
      ["text-field", ["vaadin-text-field", "(", ")"]],
      ["text-area", ["vaadin-text-area", "(", ")"]],
      ["time-picker", ["vaadin-time-picker", "(", ")"]],
    ],
  ],
  [
    "<h2>Grid</h2>",
    [
      ["grid", ["vaadin-grid", "(", ")"]],
      ["grid-column-group", ["vaadin-grid-column-group", "(", ")"]],
      ["grid-filter-column", ["vaadin-grid-filter-column", "(", ")"]],
      ["grid-selection-column", ["vaadin-grid-selection-column", "(", ")"]],
      ["grid-sort-column", ["vaadin-grid-sort-column", "(", ")"]],
      ["grid-tree-column", ["vaadin-grid-tree-column", "(", ")"]],
    ],
  ],
  [
    "<h2>Layout</h2>",
    [
      ["accordion", ["vaadin-accordion", "(", ")"]],
      ["app-layout", ["vaadin-app-layout", "(", ")"]],
      ["drawer-toggle", ["vaadin-drawer-toggle", "(", ")"]],
      ["form-layout", ["vaadin-form-layout", "(", ")"]],
      ["form-item", ["vaadin-form-item", "(", ")"]],
      [
        "horizontal-layout",
        [
          "vaadin-horizontal-layout",
          "(",
          "span",
          "(",
          "textContent",
          "Placeholder 1",
          "=",
          ")",
          "span",
          "(",
          "textContent",
          "Placeholder 2",
          "=",
          ")",
          ")",
        ],
      ],
      [
        "vertical-layout",
        [
          "vaadin-vertical-layout",
          "(",
          "span",
          "(",
          "textContent",
          "Placeholder 1",
          "=",
          ")",
          "span",
          "(",
          "textContent",
          "Placeholder 2",
          "=",
          ")",
          ")",
        ],
      ],
      [
        "split-layout horizontal",
        [
          "vaadin-split-layout",
          "(",
          "span",
          "(",
          "textContent",
          "Placeholder 1",
          "=",
          ")",
          "span",
          "(",
          "textContent",
          "Placeholder 2",
          "=",
          ")",
          ")",
        ],
        "split-layout vertical",
        [
          "vaadin-split-layout",
          "(",
          "orientation",
          "vertical",
          "=",
          "span",
          "(",
          "textContent",
          "Placeholder 1",
          "=",
          ")",
          "span",
          "(",
          "textContent",
          "Placeholder 2",
          "=",
          ")",
          ")",
        ],
      ],
    ],
  ],
  [
    "<h2>Misc</h2>",
    [
      ["avatar", ["vaadin-avatar", "(", ")"]],
      ["avatar-group", ["vaadin-avatar-group", "(", ")"]],
      ["details", ["vaadin-details", "(", ")"]],
      ["dialog", ["vaadin-dialog", "(", ")"]],
      ["icon", ["vaadin-icon", "(", "icon", "vaadin:vaadin-h", "=", ")"]],
      ["login", ["vaadin-login-overlay", "(", ")"]],
      ["menu-bar", ["vaadin-menu-bar", "(", ")"]],
      ["message-input", ["vaadin-message-input", "(", ")"]],
      ["message-list", ["vaadin-message-list", "(", ")"]],
      ["notification", ["vaadin-notification", "(", ")"]],
      ["progress-bar", ["vaadin-progress-bar", "(", ")"]],
      ["scroller", ["vaadin-scroller", "(", ")"]],
      ["upload", ["vaadin-upload", "(", ")"]],
    ],
  ],
];
